name: Download File Action
author: Alfi Maulana
description: Download a file from a URL
branding:
  icon: download
  color: white
inputs:
  url:
    description: URL of the file to download
    required: true
outputs:
  path:
    description: Path of the downloaded file
runs:
  using: node24
  main: dist/main.mjs
