name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Lefthook
        uses: threeal/setup-lefthook-action@v1.0.0

      - name: Setup pnpm
        uses: threeal/setup-pnpm-action@v2.0.0

      - name: Check pre-commit hook
        run: lefthook run pre-commit --all-files

      - name: Test
        run: pnpm vitest run

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          path: download-file-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Download file
        id: download-file
        uses: ./download-file-action
        with:
          url: https://unlicense.org/UNLICENSE

      - name: Check downloaded file
        shell: bash
        run: |
          test "${{ steps.download-file.outputs.path }}" = UNLICENSE
          openssl dgst -sha256 UNLICENSE | grep -q b5065838cbac452dfc855ba6e6e031481ad2c68406f70d21ead9321374653e6c
