name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install Lefthook
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/evilmartians/lefthook/setup.deb.sh' | sudo -E bash
          sudo apt install lefthook

      - name: Setup pnpm
        uses: threeal/setup-pnpm-action@v1.0.0
        with:
          version: 10.33.4

      - name: Check pre-commit hook
        run: lefthook run pre-commit --all-files

      - name: Test
        run: pnpm vitest run

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          path: mkdir-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Create directory
        uses: ./mkdir-action
        with:
          path: parent/child

      - name: Check directory
        shell: bash
        run: test -d parent/child
