name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, Ubuntu, macOS]
    env:
      NODE_OPTIONS: --experimental-vm-modules
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: latest

      - name: Enable Corepack
        run: corepack enable

      - name: Update Yarn
        run: yarn set version stable

      - name: Cache deps
        uses: actions/cache@v3.3.2
        with:
          path: .yarn
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install deps
        run: yarn install

      - name: Clean dist
        run: yarn clean

      - name: Build dist
        run: yarn nx build

      - name: Check diff
        run: git diff --exit-code HEAD

      - name: Generate docs
        run: yarn doc

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: docs

      - name: Test lib
        run: yarn test

  deploy:
    name: Deploy
    if: github.event_name != 'pull_request'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3.0.6

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.4
