name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, Ubuntu, macOS]
    env:
      NODE_OPTIONS: --experimental-vm-modules
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: latest

      - name: Enable Corepack
        run: corepack enable

      - name: Update Yarn
        run: yarn set version stable

      - name: Cache deps
        uses: actions/cache@v3.3.2
        with:
          path: .yarn
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install deps
        run: yarn install

      - name: Bundle dist
        run: yarn nx bundle

      - name: Check diff
        run: git diff --exit-code HEAD

      - name: Test lib
        run: yarn test

      - name: Run bin
        run: node bin/index.mjs temp
