name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-package:
    name: Test Package
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    env:
      NODE_OPTIONS: --experimental-vm-modules
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: latest

      - name: Enable Yarn
        run: corepack enable yarn

      - name: Cache deps
        uses: actions/cache@v3.3.2
        with:
          path: .yarn
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install deps
        run: yarn install

      - name: Test lib
        run: yarn test

  test-action:
    name: Test Action
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Create Directory
        uses: ./
        with:
          path: parent/child

      - name: Check Directory
        shell: bash
        run: test -d parent/child
