name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-package:
    name: Check Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20

      - name: Install Dependencies
        uses: threeal/yarn-install-action@v1.0.0

      - name: Check Format
        run: |
          corepack yarn format
          git diff --exit-code HEAD

      - name: Check Lint
        run: corepack yarn lint

  test-package:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20

      - name: Install Dependencies
        uses: threeal/yarn-install-action@v1.0.0

      - name: Test Package
        run: corepack yarn test
        env:
          NODE_OPTIONS: --experimental-vm-modules

  test-action:
    name: Test Action
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          path: mkdir-action
          sparse-checkout: |
            action.yaml
            dist
          sparse-checkout-cone-mode: false

      - name: Create Directory
        uses: ./mkdir-action
        with:
          path: parent/child

      - name: Check Directory
        shell: bash
        run: test -d parent/child
