name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-package:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: latest

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0

      - name: Test Package
        run: yarn test

  test-action:
    name: Test Action
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4.1.7
        with:
          path: mkdir-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      # Modify the following steps for testing your JavaScript action.
      # Learn more: https://docs.github.com/en/actions/automating-builds-and-tests

      - name: Create Directory
        uses: ./mkdir-action
        with:
          path: parent/child

      - name: Check Directory
        shell: bash
        run: test -d parent/child
